pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

def localProperties = new Properties()
def localPropertiesFile = new File(rootDir, 'local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { localProperties.load(it) }
}

def mapboxDownloadsToken = providers.gradleProperty('MAPBOX_DOWNLOADS_TOKEN').orNull
if (!mapboxDownloadsToken) {
    mapboxDownloadsToken = System.getenv('MAPBOX_DOWNLOADS_TOKEN')
}
if (!mapboxDownloadsToken) {
    mapboxDownloadsToken = localProperties.getProperty('MAPBOX_DOWNLOADS_TOKEN', '')
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = 'mapbox'
                password = mapboxDownloadsToken
            }
        }
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = 'RERAC'
include ':app'
